---
extends: default

rules:
  indentation:
    spaces: 2
    check-multi-line-strings: false
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
