# IMPORTANT:
#
# MUST RUN in the terminal running `skaffold dev` this will allow minikube to
# pull from local docker registry.
#
#   eval $(minikube docker-env)
#
# skaffold.yaml has to be here until this issue is resolved. Skaffold assumes
# that the bazel-out directory is in the same directory as skaffold.yaml
# https://github.com/GoogleContainerTools/skaffold/issues/7281
---
apiVersion: skaffold/v2beta29
# This file exists to let bazel know this directory is a package.
kind: Config
build:
  platforms: ['linux/amd64']
  artifacts:
    - image: ts-own-packagejson
      bazel:
        target: //:ts-own-packagejson.tar
  # local:
  #   useDockerCLI: true
deploy:
  # If you want to add a service to the development cluster you need to add the
  # k8s manifest location here.
  # Make sure the k8s manifest is only used for local development, by convention
  # create a kustomize directory named "local".
  kustomize:
    paths:
      # - ./repos/examples/go_server/k8s/local
      - ./bazel/js/examples/ts-own-packagejson/k8s/local
