---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      initContainers:
        - name: ready-db
          image: postgres:14.2
          env:
            - name: PORT
              value: "50051"
            - name: LOGLEVEL
              value: "info"
            - name: DEBUG
              value: "true"
            - name: CONNSTRING
              value: "postgres://user:password@postgres.go-server.svc:5432/database"
          command:
            [
              "sh",
              "-c",
              "until pg_isready -h postgres.go-server.svc -p 5432; do echo waiting for database; sleep 2; done;",
            ]
        - name: run-migration
          image: go-server
          env:
            - name: CONNSTRING
              value: "pgx://user:password@postgres.go-server.svc:5432/database"
            - name: MIGRATION_DIR
              value: "/etc/internal/sqlc/migrations"
          args: ["migrate"]
      containers:
        - name: go-server
          # When deployed to minikube tell it to not pull from docker registry.
          # Force it to use local docker registry (ie `docker images`)
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: LOGLEVEL
              value: "info"
            - name: DEBUG
              value: "true"
            - name: CONNSTRING
              value: "postgres://user:password@postgres.go-server.svc:5432/database"
