apiVersion: v1
kind: Namespace
metadata:
  name: go-server
---
# A service is a mechanism to allow for a stable DNS name for a set of
# dynamically allocated pods with dynamic IPs.
kind: Service
apiVersion: v1
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  selector:
    app: go-server
  ports:
    - name: go-server
      port: 80
      targetPort: 8080
---
# The deployment manages the set of running pods, they will all have dynamic IPs
# since the pods are ephemeral.
kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  replicas: 1
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: go-server
          image: go-server
          imagePullPolicy: 'Never'
          ports:
            - containerPort: 8080
