apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
  namespace: playground
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: ["/bin/sh", "-c", "env"]
      # envFrom:
      #   - configMapRef:
      #       name: special-config
  restartPolicy: Never
